version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: node_app
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   environment:
  #     DB_HOST: db
  #     DB_USER: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis
volumes:
  mysql_data:
  redis_data:
