# Sử dụng Node.js 20
FROM node:20

# Thiết lập thư mục làm việc
WORKDIR /app

# Copy package.json và cài đặt dependencies
COPY package*.json ./
RUN npm install

# Copy toàn bộ code vào container
COPY . .

# Cổng Node.js lắng nghe
EXPOSE 3000

# Câu lệnh khởi chạy ứng dụng
CMD ["node", "app.js"]
