version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
  backend:
    image: node:20
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: ['npm', 'start']
    depends_on:
      - db

volumes:
  mysql_data:
