openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication
  version: 1.0.0

paths:
  /auth/refresh-token:
    post:
      summary: Get new tokens
      description: Retrieve a new access token using a refresh token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Successfully retrieved new tokens
        '400':
          description: Invalid refresh token

  /auth/account:
    get:
      summary: Get user account information
      description: Retrieve information about the authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved account information
        '401':
          description: Unauthorized

  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
                fullName:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input data

  /auth/login:
    post:
      summary: User login
      description: Authenticate a user and return tokens.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successfully authenticated
        '401':
          description: Unauthorized

  /auth/logout:
    post:
      summary: User logout
      description: Logout a user and invalidate the refresh token.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
