openapi: 3.0.0
info:
  title: Role API
  version: 1.0.0
  description: API quản lý vai trò (roles)

paths:
  /roles/all:
    get:
      summary: Lấy danh sách tất cả vai trò
      tags:
        - Roles
      responses:
        200:
          description: Danh sách vai trò
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '65abc123def456'
                    name:
                      type: string
                      example: 'Admin'
                    description:
                      type: string
                      example: 'Quản trị viên'

  /roles/{id}:
    get:
      summary: Lấy thông tin vai trò
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID của vai trò
      responses:
        200:
          description: Chi tiết vai trò
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '65abc123def456'
                  name:
                    type: string
                    example: 'Admin'
                  description:
                    type: string
                    example: 'Quản trị viên'
        404:
          description: Không tìm thấy vai trò

    put:
      summary: Cập nhật thông tin vai trò
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID của vai trò cần cập nhật
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'Moderator'
                  description: Tên mới của vai trò
                description:
                  type: string
                  example: 'Quản lý nội dung'
                  description: Mô tả vai trò
      responses:
        200:
          description: Vai trò được cập nhật thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '65abc123def456'
                  name:
                    type: string
                    example: 'Moderator'
                  description:
                    type: string
                    example: 'Quản lý nội dung'
        400:
          description: Dữ liệu đầu vào không hợp lệ
        404:
          description: Không tìm thấy vai trò

    delete:
      summary: Xóa vai trò theo ID
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID của vai trò cần xóa
      responses:
        200:
          description: Vai trò được xóa thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Vai trò đã được xóa'
        404:
          description: Không tìm thấy vai trò

  /roles:
    post:
      summary: Tạo vai trò mới
      tags:
        - Roles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: 'Admin'
                  description: Tên vai trò cần tạo
      responses:
        201:
          description: Vai trò được tạo thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: '65abc123def456'
                  name:
                    type: string
                    example: 'Admin'
        400:
          description: Dữ liệu đầu vào không hợp lệ
