openapi: 3.0.0
info:
  title: Role API
  version: 1.0.0
  description: API quản lý vai trò (roles)

paths:
  /roles:
    post:
      summary: Tạo vai trò mới
      tags:
        - Roles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleCreate'
            example:
              name: 'Admin'
              description: 'Vai trò quản trị'
      responses:
        201:
          description: Vai trò được tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        400:
          description: Dữ liệu đầu vào không hợp lệ

  /roles/all:
    get:
      summary: Lấy danh sách tất cả vai trò (có phân trang)
      tags:
        - Roles
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            example: 1
          description: Số trang hiện tại (mặc định là 1)
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            example: 10
          description: Số lượng kết quả trên mỗi trang (mặc định là 10)
      responses:
        200:
          description: Danh sách vai trò với thông tin phân trang
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Get all roles successful!'
                  statusCode:
                    type: integer
                    example: 200
                  metaData:
                    type: object
                    properties:
                      foundRoles:
                        type: array
                        items:
                          $ref: '#/components/schemas/Role'
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
                      total:
                        type: integer
                        example: 7
        500:
          description: Lỗi máy chủ nội bộ
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Internal server error'

  /roles/{id}:
    get:
      summary: Lấy thông tin vai trò
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID của vai trò
      responses:
        200:
          description: Chi tiết vai trò
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Get role by id successful!'
                  statusCode:
                    type: integer
                    example: 200
                  metaData:
                    $ref: '#/components/schemas/Role'
        404:
          description: Không tìm thấy vai trò

    put:
      summary: Cập nhật thông tin vai trò
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID của vai trò cần cập nhật
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleUpdate'
      responses:
        200:
          description: Vai trò được cập nhật thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Get all roles successful!'
                  statusCode:
                    type: integer
                    example: 200
                  metaData:
                    type: array
                    example: [1]
        400:
          description: Dữ liệu đầu vào không hợp lệ
        404:
          description: Không tìm thấy vai trò

    delete:
      summary: Xóa vai trò theo ID
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID của vai trò cần xóa
      responses:
        200:
          description: Vai trò được xóa thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Delete role by id successful!'
                  statusCode:
                    type: integer
                    example: 200
                  metaData:
                    type: array
                    example: [1]
        404:
          description: Không tìm thấy vai trò

components:
  schemas:
    Role:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: 'ADMIN'
        description:
          type: string
          example: 'N/A'

    RoleCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: 'Admin'
        description:
          type: string
          example: 'Vai trò quản trị'

    RoleUpdate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: 'Admin'
        description:
          type: string
          example: 'Vai trò quản trị'
